### Vector calculus identities

$\Grad (fg) = f\Grad g + g\Grad f$

$\Grad (\vecA\cdot\vecB) =  \vecA\times(\Curl\vecB) + \vecB\times(\Curl\vecA) + (\vecA\cdot\Grad)\vecB  + (\vecB\cdot\Grad)\vecA$

$\Div (f\vecA) = f  (\Div \vecA) + \vecA\cdot(\Grad f)$

$\Div (\vecA\times\vecB) =  \vecB\cdot(\Curl\vecA) - \vecA\cdot(\Curl\vecB)$

$\Curl (f\vecA) = f(\Curl\vecA) - \vecA\times(\Grad f)$

$\Curl (\vecA\times\vecB) =  (\vecB\cdot\Grad)\vecA - (\vecA\cdot\Grad)\vecB + (\Div\vecB)\vecA  - (\Div\vecA)\vecB$

### Cylindrical coordinates:

$\left\{\begin{aligned}
x&=s \cos \varphi \\
y&=s \sin \varphi \\
z&=z
\end{aligned}\right.$

$\begin{aligned}
\Grad f={} & {\frac {\partial f}{\partial s  }}{\mathbf {\hat {s  }}}+{\frac {1}{s  }}{\frac {\partial f}{\partial \varphi }}{\vecfh}+{\frac {\partial f}{\partial z}}\mathbf {\hat {z}} \\[1pt]
\Div\vecA ={}&{\frac {1}{s  }}{\frac {\partial }{\partial s  }}(s  A_{s  })+{\frac {1}{s  }}{\frac {\partial A_{\varphi }}{\partial \varphi }}+{\frac {\partial A_{z}}{\partial z}}\\[1pt]
\Curl \vecA ={}& \left({\frac {1}{s  }}{\frac {\partial A_{z}}{\partial \varphi }}-{\frac {\partial A_{\varphi }}{\partial z}}\right){\mathbf {\hat {s  }}}+\left({\frac {\partial A_{s  }}{\partial z}}-{\frac {\partial A_{z}}{\partial s  }}\right){\vecfh}+{\frac {1}{s  }}\left({\frac {\partial }{\partial s  }}(s  A_{\varphi })-{\frac {\partial A_{s  }}{\partial \varphi }}\right)\mathbf {\hat {z}} \\[1pt]
\Lapl f={}& {\frac {1}{s  }}{\frac {\partial }{\partial s  }}\left(s  {\frac {\partial f}{\partial s  }}\right)+{\frac {1}{s  ^{2}}}{\frac {\partial ^{2}f}{\partial \varphi ^{2}}}+{\frac {\partial ^{2}f}{\partial z^{2}}}
\end{aligned}$

### Spherical coordinates:

$\left\{\begin{aligned}
x&=r\,\sin \theta \,\cos \varphi \\
y&=r\,\sin \theta \,\sin \varphi \\
z&=r\,\cos \theta 
\end{aligned}\right.$

$\begin{aligned}
\Grad f={}& \frac{\partial f }{\partial r} \vecrh + 
             \frac{1}{r}\frac{\partial f}{\partial \theta} \vecth +
              \frac{1}{r\sin \theta} \frac{\partial f}{\partial \varphi} \vecfh\\[1pt]
\Div\vecA ={}&\frac {1}{r^{2}}  \frac{\partial}{\partial r} \left(r^{2}A_{r}\right)+ \frac {1}{r\sin \theta }\frac{\partial}{\partial \theta }\left(\sin \theta A_{\theta }\right)+ \frac {1}{r\sin \theta } \frac{\partial A_{\varphi }}{\partial \varphi }\\[1pt]
\Curl \vecA ={}& \frac {1}{r\sin \theta } \left(\frac{\partial}{\partial \theta }\left(A_{\varphi }\sin \theta \right)-\frac{\partial A_{\theta }}{\partial \varphi }\right)\vecrh\\[1pt]
&{}+\frac {1}{r} \left(\frac {1}{\sin \theta } \frac{\partial A_{r}}{\partial \varphi }-\frac{\partial }{\partial r }\left(r A_{\varphi}\right)\right)\vecth\\[1pt] 
&{}+\frac {1}{r} \left(\frac{\partial }{\partial r }\left(r A_{\theta}\right) - \frac{\partial A_{r}}{\partial \theta }\right)\vecfh\\[1pt]
\Lapl f={}& \frac {1}{r^2} \frac{\partial }{\partial r} \left(r^{2}\frac{\partial f }{\partial r} \right) + \frac {1}{r^2\sin \theta } \frac{\partial }{\partial\theta } \left(\sin \theta \frac{\partial f}{\partial \theta }\right) + \frac {1}{r^2\sin^2 \theta }\frac{\partial^2 f }{\partial\varphi ^2}
\end{aligned}$
